#!/bin/bash

# Script to run in <course name>/info/examples
# Takes the file generated by clasifyI4xEvents.sh
# and finds examples of JSON events for each category and action

LOG_FILE=$1
I4X_CLASSIFICATION=../i4x_events.txt
PREFIX='i4x_'
HOW_MANY=10

# Read the two-column space separated file with category and action
# generated by classifyI4x.sh
# Search for $HOW_MANY corresponding i4x events in $LOG_FILE
# TODO : Find how to parse line fields

while read number category action
do
    # Each non blank line should at least
    # have a category specified
    if [ -z "$category" ]
    then
	continue
    fi

    OUTPUT_FILE="$PREFIX""$category"
    REGEXP='i4x:/.*'$category

    if [ -n "$action" ]
    then
	OUTPUT_FILE="$OUTPUT_FILE""_$action"
	REGEXP="$REGEXP"'.*'"$action"
    fi
    echo "Fetching examples of $category $action ..."
    grep --max-count=$HOW_MANY $REGEXP $LOG_FILE \
	| sed 's#"username"[ ]*:[ ]*"[^"]*"#"username":"A.N. O'"'"'Nyme"#g' \
	| sed 's#"ip"[ ]*:[ ]*"[^"]*"#"ip":"nnn.nnn.nnn"#g' > $OUTPUT_FILE'_'$HOW_MANY'.json'  

done < $I4X_CLASSIFICATION

# Finally, fetch url_change examples
echo "Fetching URL change examples"
grep --max-count=$HOW_MANY '"event_type"[ ]*:[ ]*"/[^:"]*"' $LOG_FILE \
    | sed 's#"username"[ ]*:[ ]*"[^"]*"#"username":"ANON"#g' \
    | sed 's#"ip"[ ]*:[ ]*"[^"]*"#"ip":"ANON"#g' > 'url_change_server_'$HOW_MANY'.json'  
